version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    groups:
      next-react:
        { patterns: ["next", "react", "react-dom", "eslint-config-next"] }
      development: { dependency-type: development }
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: monthly }
